spring.application.name=notification-service
spring.config.import=classpath:/config/env.properties

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DB_URL}
spring.kafka.bootstrap-servers=${KAFKA_SERVER_IP_PORT}
server.port=${SERVER_PORT:8007}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

app.kafka.topics.consumer.enroll=${KAFKA_ENROLL_TOPIC:TransactionEnroll_.*}
app.kafka.topics.consumer.withdraw=${KAFKA_ENROLL_TOPIC:TransactionWithdraw_.*}

server.servlet.context-path=/api/notification-service
outbox.scheduled=5000
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=org.ricramiel.common.dtos

spring.kafka.listener.ack-mode=manual
logging.level.org.springframework.kafka=INFO

#firebase config
firebase.config.path=${FIREBASE_CONFIG_PATH:/config/serviceAccountFCM.json}

# FCM Settings
fcm.batch.size=500
fcm.retry.attempts=3
fcm.async.enabled=true

# Logging
logging.level.com.google.firebase=INFO
logging.level.org.ricramiel.notificationservice.service.FcmService=DEBUG