spring.application.name=api-gateway
spring.config.import=classpath:/config/env.properties
spring.main.web-application-type=reactive
server.port=${SERVER_PORT}
spring.kafka.bootstrap-servers=${KAFKA_SERVER_IP_PORT:127.0.0.1:9092}

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=${USER_SERVICE_URI}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/user-service/**
spring.cloud.gateway.routes[0].filters[0].name=TokenValidationFilter
spring.cloud.gateway.routes[0].filters[0].args.tokenValidationEndpointUrl=${TOKEN_VALIDATION_URL}
spring.cloud.gateway.routes[0].filters[1].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[1].args.name=userServiceCircuitBreaker
spring.cloud.gateway.routes[0].filters[1].args.fallbackUri=forward:/fallback/user-service
spring.cloud.gateway.routes[0].filters[1].args.statusCodes[0]=500
spring.cloud.gateway.routes[0].filters[2].name=Retry
spring.cloud.gateway.routes[0].filters[2].args.retries=2
spring.cloud.gateway.routes[0].filters[2].args.statuses[0]=INTERNAL_SERVER_ERROR
spring.cloud.gateway.routes[0].filters[2].args.methods[0]=GET
spring.cloud.gateway.routes[0].filters[2].args.methods[1]=POST
spring.cloud.gateway.routes[0].filters[2].args.methods[2]=PUT
spring.cloud.gateway.routes[0].filters[2].args.methods[3]=DELETE
spring.cloud.gateway.routes[0].filters[2].args.methods[4]=PATCH
spring.cloud.gateway.routes[0].filters[2].args.backoff.firstBackoff=100ms
spring.cloud.gateway.routes[0].filters[2].args.backoff.maxBackoff=400ms
spring.cloud.gateway.routes[0].filters[2].args.backoff.factor=2
spring.cloud.gateway.routes[0].filters[2].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[1].id=core-api
spring.cloud.gateway.routes[1].uri=${CORE_API_URI}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/core-api/**
spring.cloud.gateway.routes[1].filters[0].name=TokenValidationFilter
spring.cloud.gateway.routes[1].filters[0].args.tokenValidationEndpointUrl=${TOKEN_VALIDATION_URL}
spring.cloud.gateway.routes[1].filters[1].name=CircuitBreaker
spring.cloud.gateway.routes[1].filters[1].args.name=coreApiCircuitBreaker
spring.cloud.gateway.routes[1].filters[1].args.fallbackUri=forward:/fallback/core-api
spring.cloud.gateway.routes[1].filters[1].args.statusCodes[0]=500
spring.cloud.gateway.routes[1].filters[2].name=Retry
spring.cloud.gateway.routes[1].filters[2].args.retries=2
spring.cloud.gateway.routes[1].filters[2].args.statuses[0]=INTERNAL_SERVER_ERROR
spring.cloud.gateway.routes[1].filters[2].args.methods[0]=GET
spring.cloud.gateway.routes[1].filters[2].args.methods[1]=POST
spring.cloud.gateway.routes[1].filters[2].args.methods[2]=PUT
spring.cloud.gateway.routes[1].filters[2].args.methods[3]=DELETE
spring.cloud.gateway.routes[1].filters[2].args.methods[4]=PATCH
spring.cloud.gateway.routes[1].filters[2].args.backoff.firstBackoff=100ms
spring.cloud.gateway.routes[1].filters[2].args.backoff.maxBackoff=400ms
spring.cloud.gateway.routes[1].filters[2].args.backoff.factor=2
spring.cloud.gateway.routes[1].filters[2].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[2].id=credit-service
spring.cloud.gateway.routes[2].uri=${CREDIT_SERVICE_URI}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/credit-service/**
spring.cloud.gateway.routes[2].filters[0].name=TokenValidationFilter
spring.cloud.gateway.routes[2].filters[0].args.tokenValidationEndpointUrl=${TOKEN_VALIDATION_URL}
spring.cloud.gateway.routes[2].filters[1].name=CircuitBreaker
spring.cloud.gateway.routes[2].filters[1].args.name=creditServiceCircuitBreaker
spring.cloud.gateway.routes[2].filters[1].args.fallbackUri=forward:/fallback/credit-service
spring.cloud.gateway.routes[2].filters[1].args.statusCodes[0]=500
spring.cloud.gateway.routes[2].filters[2].name=Retry
spring.cloud.gateway.routes[2].filters[2].args.retries=2
spring.cloud.gateway.routes[2].filters[2].args.statuses[0]=INTERNAL_SERVER_ERROR
spring.cloud.gateway.routes[2].filters[2].args.methods[0]=GET
spring.cloud.gateway.routes[2].filters[2].args.methods[1]=POST
spring.cloud.gateway.routes[2].filters[2].args.methods[2]=PUT
spring.cloud.gateway.routes[2].filters[2].args.methods[3]=DELETE
spring.cloud.gateway.routes[2].filters[2].args.methods[4]=PATCH
spring.cloud.gateway.routes[2].filters[2].args.backoff.firstBackoff=100ms
spring.cloud.gateway.routes[2].filters[2].args.backoff.maxBackoff=400ms
spring.cloud.gateway.routes[2].filters[2].args.backoff.factor=2
spring.cloud.gateway.routes[2].filters[2].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[3].id=transaction-service
spring.cloud.gateway.routes[3].uri=${TRANSACTION_SERVICE_URI}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/transaction-service/**
spring.cloud.gateway.routes[3].filters[0].name=TokenValidationFilter
spring.cloud.gateway.routes[3].filters[0].args.tokenValidationEndpointUrl=${TOKEN_VALIDATION_URL}

spring.cloud.gateway.routes[4].id=preferences-service
spring.cloud.gateway.routes[4].uri=${PREFERENCES_SERVICE_URI}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/preferences-service/**
spring.cloud.gateway.routes[4].filters[0].name=TokenValidationFilter
spring.cloud.gateway.routes[4].filters[0].args.tokenValidationEndpointUrl=${TOKEN_VALIDATION_URL}

spring.cloud.gateway.routes[5].id=notification-service
spring.cloud.gateway.routes[5].uri=${NOTIFICATION_SERVICE_URI}
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/notification-service/**
spring.cloud.gateway.routes[5].filters[0].name=TokenValidationFilter
spring.cloud.gateway.routes[5].filters[0].args.tokenValidationEndpointUrl=${TOKEN_VALIDATION_URL}

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins[0]=${CLIENT_SECURE_URL}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins[1]=${WORKER_SECURE_URL}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins[2]=${API_SECURE_URL}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins[3]=${CLIENT_URL}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins[4]=${WORKER_URL}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins[5]=${API_URL}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns[0]=http://localhost:*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns[1]=http://127.0.0.1:*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].max-age=3600

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=org.ricramiel.common.dtos

resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.sliding-window-size=20
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.failure-rate-threshold=70
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.permitted-number-of-calls-in-half-open-state=5
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.circuitbreaker.instances.coreApiCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.coreApiCircuitBreaker.sliding-window-size=20
resilience4j.circuitbreaker.instances.coreApiCircuitBreaker.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.coreApiCircuitBreaker.failure-rate-threshold=70
resilience4j.circuitbreaker.instances.coreApiCircuitBreaker.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.coreApiCircuitBreaker.permitted-number-of-calls-in-half-open-state=5
resilience4j.circuitbreaker.instances.coreApiCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.circuitbreaker.instances.creditServiceCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.creditServiceCircuitBreaker.sliding-window-size=20
resilience4j.circuitbreaker.instances.creditServiceCircuitBreaker.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.creditServiceCircuitBreaker.failure-rate-threshold=70
resilience4j.circuitbreaker.instances.creditServiceCircuitBreaker.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.creditServiceCircuitBreaker.permitted-number-of-calls-in-half-open-state=5
resilience4j.circuitbreaker.instances.creditServiceCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true
