spring.application.name=api-gateway
spring.config.import=classpath:/config/env.properties
spring.main.web-application-type=reactive
server.port=${SERVER_PORT}
spring.kafka.bootstrap-servers=${KAFKA_SERVER_IP_PORT:127.0.0.1:9092}

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=${USER_SERVICE_URI}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/user-service/**
spring.cloud.gateway.routes[0].filters[0].name=TokenValidationFilter
spring.cloud.gateway.routes[0].filters[0].args.tokenValidationEndpointUrl=${TOKEN_VALIDATION_URL}

spring.cloud.gateway.routes[1].id=core-api
spring.cloud.gateway.routes[1].uri=${CORE_API_URI}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/core-api/**
spring.cloud.gateway.routes[1].filters[0].name=TokenValidationFilter
spring.cloud.gateway.routes[1].filters[0].args.tokenValidationEndpointUrl=${TOKEN_VALIDATION_URL}

spring.cloud.gateway.routes[2].id=credit-service
spring.cloud.gateway.routes[2].uri=${CREDIT_SERVICE_URI}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/credit-service/**
spring.cloud.gateway.routes[2].filters[0].name=TokenValidationFilter
spring.cloud.gateway.routes[2].filters[0].args.tokenValidationEndpointUrl=${TOKEN_VALIDATION_URL}

spring.cloud.gateway.routes[3].id=transaction-service
spring.cloud.gateway.routes[3].uri=${TRANSACTION_SERVICE_URI}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/transaction-service/**
spring.cloud.gateway.routes[3].filters[0].name=TokenValidationFilter
spring.cloud.gateway.routes[3].filters[0].args.tokenValidationEndpointUrl=${TOKEN_VALIDATION_URL}

spring.cloud.gateway.routes[4].id=preferences-service
spring.cloud.gateway.routes[4].uri=${PREFERENCES_SERVICE_URI}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/preferences-service/**
spring.cloud.gateway.routes[4].filters[0].name=TokenValidationFilter
spring.cloud.gateway.routes[4].filters[0].args.tokenValidationEndpointUrl=${TOKEN_VALIDATION_URL}

spring.cloud.gateway.routes[5].id=notification-service
spring.cloud.gateway.routes[5].uri=${NOTIFICATION_SERVICE_URI}
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/notification-service/**
spring.cloud.gateway.routes[5].filters[0].name=TokenValidationFilter
spring.cloud.gateway.routes[5].filters[0].args.tokenValidationEndpointUrl=${TOKEN_VALIDATION_URL}

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins[0]=${CLIENT_SECURE_URL}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins[1]=${WORKER_SECURE_URL}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins[2]=${API_SECURE_URL}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins[3]=${CLIENT_URL}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins[4]=${WORKER_URL}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins[5]=${API_URL}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].max-age=3600

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=org.ricramiel.common.dtos