apiVersion: 1

datasources:
  - name: Monitoring TimescaleDB
    uid: monitoring-timescaledb
    type: postgres
    access: proxy
    url: monitoring-db:5432
    user: admin
    secureJsonData:
      password: password
    jsonData:
      database: monitoring_db
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    editable: true
