FROM node:22-bookworm-slim
WORKDIR /repo

RUN corepack enable

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml tsconfig.base.json ./
COPY packages ./packages
COPY apps ./apps
COPY tools ./tools

RUN pnpm install --frozen-lockfile
RUN pnpm --filter @fins/ui-kit build \
    && pnpm --filter @fins/api build \
    && pnpm --filter @fins/entities build

EXPOSE 5173 5174 5175
