spring.application.name=core-api
spring.config.import=classpath:/config/env.properties
spring.kafka.topic.transaction=${TRANSACTION_TOPIC}
spring.kafka.topic.withdraw_transaction=${TRANSACTION_WITHDRAW}
spring.kafka.topic.enroll_transaction=${TRANSACTION_ENROLL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.kafka.bootstrap-servers=${KAFKA_SERVER_IP_PORT}
server.port=${SERVER_PORT:8001}

spring.jpa.hibernate.ddl-auto=update

#logging.level.org.springframework.security=Trace
#logging.level.org.springframework.web=DEBUG
#logging.level.org.ricramiel=DEBUG

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=org.ricramiel.common.dtos

server.servlet.context-path=/api/core-api

outbox.scheduled=5000
app.kafka.destination=${KAFKA_DESTINATION:credit}
type.withdraw=${TYPE_WITHDRAW:withdraw}
type.enroll=${TYPE_ENROLL:enroll}
app.kafka.topics.consumer.enroll=${KAFKA_ENROLL_TOPIC:TransactionEnroll_.*}
app.kafka.topics.consumer.withdraw=${KAFKA_WITHDRAW_TOPIC:TransactionWithdraw_.*}

spring.kafka.listener.ack-mode=manual
logging.level.org.springframework.kafka=INFO

external.currency.url=https://www.cbr-xml-daily.ru/daily_json.js
application.master_account.id = ${MASTER_CARD_ACCOUNT:18f35126-66c0-4997-9922-39c70e924634}

chaos.http.enabled=${CHAOS_HTTP_ENABLED:false}
chaos.http.even-minute-threshold=${CHAOS_HTTP_EVEN_MINUTE_THRESHOLD:70}
chaos.http.odd-minute-threshold=${CHAOS_HTTP_ODD_MINUTE_THRESHOLD:30}
chaos.http.status=${CHAOS_HTTP_STATUS:500}
chaos.kafka.enabled=${CHAOS_KAFKA_ENABLED:false}
chaos.kafka.even-minute-threshold=${CHAOS_KAFKA_EVEN_MINUTE_THRESHOLD:70}
chaos.kafka.odd-minute-threshold=${CHAOS_KAFKA_ODD_MINUTE_THRESHOLD:30}

#caching
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500, expireAfterWrite=2h
